name: yaru_colors_example
description: Yaru Colors example app
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flex_color_picker: ^2.5.0
  flutter:
    sdk: flutter
  handy_window: ^0.1.2
  yaru: ^0.3.0
  yaru_colors: ^0.1.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  package_config: ^2.0.2
  path: ^1.8.0

flutter:
  uses-material-design: true
