name: yaru_colors

packages:
  - packages/**

ignore:
  - synthetic_package

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  # analyze all packages
  analyze: >
    melos exec -c 1 -- \
      flutter analyze --fatal-infos .

  # collect coverage information for all packages
  coverage: >
    melos exec -c 1 --fail-fast --dir-exists=test --ignore='*builder*' -- \
      flutter test --coverage && melos run coverage:cleanup

  # cleanup generated files from coverage
  coverage:cleanup: >
    melos exec --file-exists=coverage/lcov.info -- \
      lcov --remove coverage/lcov.info '**/*.g.dart' -o coverage/lcov.info

  # format all packages
  format: >
    find . -name '*.dart' \
      ! -name '*.g.dart' \
      ! -path '*/.*/*' \
      | xargs dart format --set-exit-if-changed

  # run build_runner to generate code in all packages
  generate: >
    melos exec -c 1 --fail-fast --depends-on=build_runner -- \
      flutter pub run build_runner build --delete-conflicting-outputs

  # run tests in all packages
  test: >
    melos exec -c 1 --fail-fast --dir-exists=test -- \
      dart test
    melos exec -c 1 --fail-fast --dir-exists=integration_test -- \
      flutter test integration_test -d linux

  # updates goldens in all packages
  update-goldens: >
    melos exec -c 1 --fail-fast --dir-exists=golden_test -- \
      flutter test --update-goldens golden_test
