name: yaru_colors
description: A collection of Yaru color palettes for Flutter.
homepage: https://github.com/ubuntu/yaru_colors.dart
repository: https://github.com/ubuntu/yaru_colors.dart
issue_tracker: https://github.com/ubuntu/yaru_colors.dart/issues
version: 0.1.5

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  meta: ^1.7.0
  yaru_color_generator: ^0.1.0

dev_dependencies:
  build_runner: ^2.1.10
  lints: ^1.0.0
  test: ^1.21.4
  yaru_color_builder: ^0.1.0
