name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo snap install flutter --classic
      - run: echo "$HOME/snap/flutter/common/flutter/.pub-cache/bin" >> $GITHUB_PATH
      - run: flutter doctor -v
      - uses: bluefireteam/melos-action@v1
      - run: flutter build linux -v
        working-directory: packages/yaru_colors/example

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v1
      - run: flutter doctor -v
      - run: flutter build web -v
        working-directory: packages/yaru_colors/example
